#!/usr/bin/env bash
oldrev=$1
newrev=$2


run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

echo "Installing dependencies..."
run "npm install --only=prod"

# # clear cached assets (unversioned/ignored files)
# run "git clean -x -f -- public/stylesheets public/javascripts"

# # clean unversioned files from vendor/plugins (e.g. old submodules)
# run "git clean -d -f -- vendor/plugins"
